<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Branches\Validators\" />
    <Folder Include="Features\Branches\Queries\" />
    <Folder Include="Features\Employees\DTOs\" />
    <Folder Include="Features\Employees\Queries\" />
    <Folder Include="Features\InventoryTransactions\Commands\" />
    <Folder Include="Features\InventoryTransactions\Validators\" />
    <Folder Include="Features\Products\DTOs\" />
    <Folder Include="Features\Products\Queries\" />
  </ItemGroup>

</Project>
